### ISSUE TITLE
DocumentContext#json() Returns Invalid JSON When A JSON Object Is Parsed

### ISSUE THREAD

**Issue by ryanlevell** [jayway/JsonPath#217] opened 2016-04-06 15:46 UTC
When a JSON **object** is parsed, `DocumentContext#json()` returns invalid JSON, possibly `java.util.Map#toString()`.
When a JSON **array** is parsed,  `DocumentContext#json()` returns returns valid JSON.
#### Java

``` java
// json object
System.out.println("JSON Object: " + JsonPath.parse("{a: \"123\"}").json());
// json array
System.out.println("JSON Array: " + JsonPath.parse("[{a: \"123\"}]").json());
```
#### Console

``` bash
JSON Object: {a=123} # Map#toString()
JSON Array: [{"a":"123"}] # Valid JSON
```

**Comment by ryanlevell** [comment] 2016-04-06 16:14
As a workaround, `ReadContext#jsonString()` works as expected for JSON arrays and objects.

**Comment by kallestenflo** [comment] 2016-04-06 16:17
This is by design. The `.json()` method returns the JSON document as parsed by the JsonProvider The `.jsonString()` returns the JSON document as a String.

**Comment by ryanlevell** [comment] 2016-04-06 16:19
Thanks for the clarification.

**Comment by jochenberger** [comment] 2017-03-23 13:26
@kallestenflo close this?

**Closed** 2017-03-23 14:26 UTC
