### ISSUE TITLE
update pom to point to json-smart 2.2 (to pull updated asm dependency)

### ISSUE THREAD

**Issue by orphean-zz** [jayway/JsonPath#116] opened 2015-08-25 15:56 UTC
Hello, the current pom has a depdency on json-smart 2.1.1, which in turn, has a direct dependency on {net.minidev, asm, 1.0.2} which in turn pulls in {asm, asm, 3.3.1}.

This unfortunately causes package namespace pollution as it has the package structure "org.objectweb.asm.*".

If you change the pom to have a dependency on json-smart-2.2, it correctly has a dependency on {net.minidev, accessors-smart} which correcstly pulls in the asm dependnecy by specifying org.object.web.asm

**Comment by jochenberger** [comment] 2015-08-26 07:06
Duplicate of #85.

**Comment by orphean-zz** [comment] 2015-08-26 07:17
thank you. any idea when this will be pushed to maven central?

**Comment by twicksell** [comment] 2015-09-24 22:04
+1, would like to see the 2.0.1 release with this fix as soon as possible to avoid this issue. Any blockers to release?

**Comment by artembilan** [comment] 2015-09-24 22:06
The reference issue https://jira.spring.io/browse/INT-3832.
And yes, that means +1 for release

**Comment by kallestenflo** [comment] 2015-09-29 20:07
resolved in #108

**Closed by kallestenflo** 2015-09-29 20:07 UTC
