### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by tranwarpxl** [jayway/JsonPath#94] opened 2015-05-30 05:36 UTC
One of our QA servers ran out of memory, looks like there is a memory leak in Cache.java.
A simple single-threaded program to reproduce the issue is below.
I think it is better to allow the user to disable the cache, and let the user create (and cache) CompiledPath instances.

    public static void main(String[] arg) {
        Cache cache = new Cache(200);
        Path dummy = new CompiledPath(null, false);
        for (int i = 0; i < 10000; ++i) {
           String key = String.valueOf(i);
           cache.get(key);
           cache.put(key, dummy);
        }
        System.out.println("cache size: " + cache.size());
    }

**Comment by jochenberger** [comment] 2015-08-10 08:25
We could switch to a `Map<String, SoftReference<Path>>` for the cache.

**Comment by javierpajaro** [comment] 2015-09-20 16:24
Hi @jochenberger,

Was this fixed?

Javier.

**Comment by jochenberger** [comment] 2015-09-30 08:38
No, the issue is still open. This isn't a memory leak however, the issue title is misleading.

**Comment by gauravgupta2** [comment] 2015-10-08 15:47
Adding the comment here, since it seems like a similar issue. I'm using JsonPath to parse around a million jsons using 5 threads. The readThenAddKey methods kills the concurrency. The app actually spends 80% of the time in the readThenAddKey method. I experimented with Map<String, SoftReference<Path>> as Cache and it resolves the issue (the app runs 5 times faster).

@kallestenflo  I see that you tried to fix the Cache class, but I think the LRU eviction implementation in the Cache doesn't help the concurrency

I think using a combination of the suggestions in this thread will fix the problem:
1. Allow a configuration parameter to enable or disable cache
2. Use the Map<String, SoftReference<Path>> as default Cache implementation
3. Allow plugin-in a Cache implementation using spi?

I can create a pull request if there is no other good reason to keep the Cache implementation

**Comment by jochenberger** [comment] 2015-10-09 08:41
I'm starting to wonder if we actually want an LRU cache. Wouldn't an LFU cache be better? 
This kind of thoughts makes me think that a pluggable implementation would be a good idea actually. We could then provide a NoOp cache that can be used instead when working in low-memory environments.

**Comment by kallestenflo** [comment] 2015-10-09 10:12
I think a Cache SPI is the way to go. There are some changes that has to be done if it should be configured via Configuration.

**Comment by javierpajaro** [comment] 2015-10-09 10:59
what if you escape the jvm? Check this
http://www.javacodegeeks.com/2012/12/escaping-the-jvm-heap-for-memory-intensive-applications.html

**Comment by kallestenflo** [comment] 2015-10-09 12:31
That is not an option. If we provide SPI people are free to do what they want.

**Comment by orangeven** [comment] 2015-10-09 13:53
There is a bug in the implementation of com.jayway.jsonpath.internal.Cache. 
The maximal size of the internal Map and Deque could be exceeded. The bug is easy to reproduce, just run: 
```
IntStream.range(0,1000).forEach(i -> {
      PathCompiler.compile("test" + i);
    });
 ```
and observe at the end the size of the Map and Deque. The keys are added twist to the Deque. 
I am able to observe the Deque with 190K elements on a test server. Lots of tomcat threads are blocked since it takes a lot of time to add/delete element from the Deque and Map. The server comes at the end to OutOfMemoryException.

**Comment by feffef** [comment] 2015-10-09 15:09
...the root cause of the problem is that `com.jayway.jsonpath.internal.Cache#get(String)` will add the key to the queue to the beginning of the queue even though no entry with that key is contained in the map. 

That's how you end up with duplicate keys in the queue, which causes the `map.remove(removeLast())` in `com.jayway.jsonpath.internal.Cache#put(String, Path)` to not always actually remove stuff from the map, and the configured limit of 200 is not respected at all.

**Comment by trajano** [comment] 2015-10-13 04:01
Would it make sense to use JCache as the caching API. It will be part of Java EE 8 anyway.

**Comment by orangeven** [comment] 2015-10-19 09:30
Is there a plan for the 2.1 release?

**Comment by kallestenflo** [comment] 2015-11-04 18:26
Minor fix in cache and new CacheProvider SPI.

**Closed by kallestenflo** 2015-11-04 18:26 UTC
Labels: BUG
